### ISSUE TITLE
User cannot rm some applications

### ISSUE THREAD

**Issue by hei-teacher** [jcloudify/jcloudify#2]
Gets HTTP 404 when removing 
![Uploading Capture d’écran 2024-09-05 à 16.13.22.png…](ahoana)

**Comment by hei-teacher** [comment]
<img width="1283" alt="Capture d’écran 2024-09-05 à 16 13 16" src="https://github.com/user-attachments/assets/78849cf7-fbda-41e3-94e8-25655ca3ab38">

**Comment by Onitsiky** [comment]
@hei-teacher does this project already has created environments or not ?
